import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/layout/Navigation";
import "../styles/animation.css";
import Footer from "@/components/layout/Footer";
import { getLocale, getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const messages = await getMessages();
  return (
    <html lang={locale}>
      <body className={`${geistSans.variable} ${geistMono.variable} select-none `}>
        <NextIntlClientProvider messages={messages}>
          <div className="fixed z-50 h-fit bg-white w-full">
            <Navigation />
            <hr className="inset-0 col-span-12" />
          </div>
          <div className="w-full mt-[5.5rem] grid grid-cols-12">
            {children}
          </div>
          <div className="">
            <Footer />
          </div>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
