import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/layout/Navigation";
import "../styles/animation.css";
import Footer from "@/components/layout/Footer";
import { getLocale, getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const messages = await getMessages();
  return (
    <html lang={locale}>
      <body className={`${geistSans.variable} ${geistMono.variable} select-none  `}>
        <NextIntlClientProvider messages={messages}>
          <div className="flex flex-col items-center">
            <div className="fixed z-50 h-fit bg-white w-full">
              <div className="w-[100rem] mx-auto">
                <Navigation />
              </div>
              <hr />
            </div>
            <div className="max-w-[100rem] mt-[5.5rem]">
              {children}
            </div>
            <div className="w-[100rem]">
              <Footer />
            </div>
          </div>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
